# Generated by Django 5.0.3 on 2024-04-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(choices=[('160 X 230', '160 X 230'), ('260 X 330', '260 X 330'), ('1160 X 930', '1160 X 930')], default='160 X 230', max_length=100)),
                ('paid', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
