# Generated by Django 5.0.3 on 2024-03-26 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('120 x 140', '120 x 140'), ('130 x 200', '130 x 200'), ('500 x 600', '500 x 600')], default='120 x 140', max_length=50)),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('data_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.IntegerField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(choices=[('Nürnberg', 'Nürnberg'), ('Erlangen', 'Erlangen'), ('Fürth', 'Fürth'), ('Schvabach', 'Schvabach')], default='Nürnberg', max_length=50)),
                ('street', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('house_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.CharField(max_length=200)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.order')),
            ],
        ),
    ]
