# Generated by Django 5.0.3 on 2024-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default=1, upload_to='photo/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
