# Generated by Django 5.0.3 on 2024-05-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='client_numer',
            new_name='username',
        ),
    ]
