# Generated by Django 5.0.3 on 2024-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_shopuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
