# Generated by Django 5.0.3 on 2024-05-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_shopuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='password1',
            field=models.CharField(default=78, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
